name: ledgerflow
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11

  # Data generation
  - faker=24.11.0

  # Data manipulation
  - pandas=2.2.2
  - numpy=1.26.4

  # Database drivers
  - psycopg2=2.9.9          # PostgreSQL driver (production / Docker)
  - sqlalchemy=2.0.30

  # Local dev database (no server needed)
  - duckdb=0.10.3
  - pip:
    - duckdb-engine==0.13.2   # SQLAlchemy dialect for DuckDB

  # dbt (transform layer)
  - pip:
    - dbt-core==1.8.3
    - dbt-postgres==1.8.2
    - dbt-duckdb==1.8.1       # dbt adapter for local DuckDB dev

  # Data quality
  - pip:
    - great-expectations==0.18.19

  # AWS SDK
  - boto3=1.34.131

  # Utilities
  - python-dotenv=1.0.1
  - pip=24.0

  # Jupyter (optional, for exploration)
  - jupyterlab=4.2.1
  - ipykernel=6.29.4
